sudo: false

language: ruby
rvm:
  - 2.0.0
  - 2.1
  - 2.2
  - 2.2.4
  - 2.3.0

before_install: gem install bundler -v 1.16.1

install:
  - bundle install --retry=3

script:
  - bundle exec rspec
  - bundle exec rubocop -D --format simple lib spec

os:
  - linux
  - osx
